<a href="https://colab.research.google.com/github/Abhishekconfused/Learningthings/blob/main/numpymatplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
arrd1= np.array([1,2,3,4])
arrd1

array([1, 2, 3, 4])

In [ ]:
type(arrd1)

numpy.ndarray

In [ ]:
arrd1.ndim

1

In [ ]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.size

8

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
np.ones([5])#its float

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.zeros((2,3),dtype=str)

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [ ]:
bool('')

False

In [ ]:
np.empty((3,4))

array([[5.01665724e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

arange()

In [ ]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
arr3=np.reshape(np.arange(1,13),(3,2,2))
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arr4=np.ravel(arr2)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr2.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
arr5=np.reshape(np.arange(1,10),(3,3))
arr6=np.reshape(np.arange(1,10),(3,3))
arr5+arr6

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.add(arr5,arr6)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.subtract(arr5,arr6)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr5@arr6#matrix multiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

WE CAN ALSO USE np.sum(arr5)

In [ ]:
arr5.max()

9

In [ ]:
arr5.argmax()#index of maximum value

8

In [ ]:
arr5.max(axis=0)#gives maximum value in each column

array([7, 8, 9])

In [ ]:
arr5.max(axis=1)#gives maximum value in each row

array([3, 6, 9])

In [ ]:
arr5.sum()

45

In [ ]:
arr5.sum(axis=0)#sum in each column

array([12, 15, 18])

In [ ]:
arr5.sum(axis=1)#sum in each row

array([ 6, 15, 24])

In [ ]:
arr5.mean()

5.0

In [ ]:
arr5.mean(axis=0)

array([4., 5., 6.])

In [ ]:
np.std(arr5)

2.581988897471611

In [ ]:
np.log(arr5)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
np.log10(arr5)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

LETS DO SLICING

In [ ]:
mx=np.arange(1,101).reshape(10,10)

In [ ]:
mx[0,1]

2

In [ ]:
mx[0:2,0:2]

array([[ 1,  2],
       [11, 12]])

In [ ]:
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
mx[:,1]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [ ]:
mx[0:9:2,0:9:2]

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

Lets concate

In [ ]:
np.concatenate((arr5,arr6))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.concatenate((arr5,arr6),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [ ]:
np.vstack((arr5,arr6))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.hstack((arr5,arr6))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [ ]:
list1=np.split(arr5,3)

In [ ]:
list1[0]

array([[1, 2, 3]])

In [ ]:
np.split(arr5,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

LETS DO TIGONOMETRY


In [ ]:
np.sin(180)

-0.8011526357338304

In [ ]:
np.sin(np.pi/20)

0.15643446504023087

Random

In [ ]:
import random

In [ ]:
np.random.random((1,2))

array([[0.99426964, 0.80313026]])

In [ ]:
np.random.randint(1,100,(3,3))

array([[ 1, 69, 53],
       [25, 37, 47],
       [37, 48, 82]])

In [ ]:
np.random.seed(10)
np.random.randint(1,100,(3,3))

array([[10, 16, 65],
       [29, 90, 94],
       [30,  9, 74]])

In [ ]:
np.random.seed(1)
np.random.randint(1,100,(3,3))

array([[38, 13, 73],
       [10, 76,  6],
       [80, 65, 17]])

In [ ]:
np.random.seed(10)#seed function fixes the random
np.random.randint(1,100,(3,3))

array([[10, 16, 65],
       [29, 90, 94],
       [30,  9, 74]])

In [ ]:
np.random.rand(3,3)

array([[0.16911084, 0.08833981, 0.68535982],
       [0.95339335, 0.00394827, 0.51219226],
       [0.81262096, 0.61252607, 0.72175532]])

In [ ]:
np.random.randn(3,3)

array([[ 0.46964093, -0.23396259,  0.35365794],
       [ 1.78370094, -0.35030121, -0.9896496 ],
       [-0.63425417,  1.89876222,  1.99652279]])

In [ ]:
x=[1,2,3,4]

In [ ]:
np.random.choice(x)

1

In [ ]:
np.random.permutation(x)

array([1, 2, 3, 4])

CHARACTER AND STRING OPERATIONS

In [ ]:
ch="HI BYE "
ch1="Hello"

In [ ]:
np.char.add(ch,ch1)

array('HI BYE Hello', dtype='<U12')

In [ ]:
np.char.lower(ch)

array('hi bye ', dtype='<U7')

In [ ]:
np.char.split(ch)

array(list(['HI', 'BYE']), dtype=object)

In [ ]:
np.char.splitlines(ch)

array(list(['HI BYE ']), dtype=object)

In [ ]:
np.char.replace(ch,"HI","BYE")

array('BYE BYE ', dtype='<U8')

In [ ]:
np.equal(ch,ch1)

False

In [ ]:
np.char.count(ch,"H")

array(1)

In [ ]:
np.char.find(ch,'E')

array(5)